import { useMemo, useState } from "react";

import { emergencyRepository } from "../repositories/emergencyRepository";
import type { Emergency, EmergencyInput } from "../types/emergency";

const emptyForm: EmergencyInput = { nombre_lugar: "", ubicacion: "", latitud: undefined, longitud: undefined, descripcion: "", telefono: "", tipo: "", registrado_por: "", estado: "ACTIVO" };
const pageSize = 6;

function EmergencyForm({ value, onCancel, onSave }: { value: EmergencyInput; onCancel: () => void; onSave: (value: EmergencyInput) => void }) {
  const [form, setForm] = useState(value);
  const set = (key: keyof EmergencyInput, raw: string) => setForm((current) => ({ ...current, [key]: key === "latitud" || key === "longitud" ? (raw === "" ? undefined : Number(raw)) : raw }));
  return <form className="module-form" onSubmit={(event) => { event.preventDefault(); onSave(form); }}>
    <label>Tipo<input required value={form.tipo} onChange={(e) => set("tipo", e.target.value)} /></label><label>Lugar<input required value={form.nombre_lugar} onChange={(e) => set("nombre_lugar", e.target.value)} /></label>
    <label className="module-form__wide">Descripción<textarea required value={form.descripcion} onChange={(e) => set("descripcion", e.target.value)} /></label><label>Ubicación<input required value={form.ubicacion} onChange={(e) => set("ubicacion", e.target.value)} /></label>
    <label>Teléfono<input required value={form.telefono} onChange={(e) => set("telefono", e.target.value)} /></label><label>Latitud<input type="number" step="any" value={form.latitud ?? ""} onChange={(e) => set("latitud", e.target.value)} /></label><label>Longitud<input type="number" step="any" value={form.longitud ?? ""} onChange={(e) => set("longitud", e.target.value)} /></label>
    <label>Registrado por<input required value={form.registrado_por} onChange={(e) => set("registrado_por", e.target.value)} /></label><label>Estado<select value={form.estado} onChange={(e) => set("estado", e.target.value)}><option>ACTIVO</option><option>INACTIVO</option></select></label>
    <div className="module-form__actions"><button type="button" className="module-button module-button--secondary" onClick={onCancel}>Cancelar</button><button className="admin-button">Guardar emergencia</button></div>
  </form>;
}

export default function EmergenciesPage() {
  const [items, setItems] = useState<Emergency[]>(() => emergencyRepository.list());
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("TODOS"); const [type, setType] = useState("TODOS"); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Emergency | null | "new">(null); const [detail, setDetail] = useState<Emergency | null>(null);
  const types = useMemo(() => [...new Set(items.map((item) => item.tipo))], [items]);
  const visible = items.filter((item) => `${item.PK_id} ${item.tipo} ${item.descripcion} ${item.ubicacion} ${item.registrado_por}`.toLowerCase().includes(query.toLowerCase()) && (status === "TODOS" || item.estado === status) && (type === "TODOS" || item.tipo === type));
  const pages = Math.max(1, Math.ceil(visible.length / pageSize)); const records = visible.slice((page - 1) * pageSize, page * pageSize);
  const refresh = () => { setItems(emergencyRepository.list()); setPage(1); };
  const save = (form: EmergencyInput) => { if (editing === "new") emergencyRepository.create(form); else if (editing) emergencyRepository.update(editing.PK_id, form); setEditing(null); refresh(); };
  const validLocations = items.filter((item) => Number.isFinite(item.latitud) && Number.isFinite(item.longitud));
  const byType = types.map((name) => ({ name, count: items.filter((item) => item.tipo === name).length }));
  const today = new Date().toDateString(); const todayCount = items.filter((item) => new Date(item.fecha_registro).toDateString() === today).length;
  return <section className="module-page">
    <div className="module-heading"><div><p className="eyebrow">Gestión</p><h1>Emergencias</h1><p>Registra, localiza y administra las emergencias del sistema turístico.</p></div><button className="admin-button" onClick={() => setEditing("new")}>Registrar Emergencia</button></div>
    <div className="module-stats"><article><span>Total</span><strong>{items.length}</strong><small>Emergencias registradas</small></article><article><span>Activas</span><strong>{items.filter((i) => i.estado === "ACTIVO").length}</strong><small>Requieren seguimiento</small></article><article><span>Hoy</span><strong>{todayCount}</strong><small>Registros del día</small></article><article><span>Ubicables</span><strong>{validLocations.length}</strong><small>Con coordenadas válidas</small></article></div>
    <div className="emergency-insights"><article className="module-panel"><h2>Ubicación de emergencias</h2>{validLocations.length ? <ul className="location-list">{validLocations.slice(0, 5).map((item) => <li key={item.PK_id}><strong>{item.nombre_lugar}</strong><span>{item.latitud!.toFixed(5)}, {item.longitud!.toFixed(5)}</span></li>)}</ul> : <p className="module-empty">No hay emergencias con coordenadas válidas para mostrar.</p>}</article><article className="module-panel"><h2>Emergencias por categoría</h2>{byType.length ? <ul className="bar-list">{byType.map(({ name, count }) => <li key={name}><span>{name}</span><i><b style={{ width: `${(count / items.length) * 100}%` }} /></i><strong>{count}</strong></li>)}</ul> : <p className="module-empty">Sin categorías registradas.</p>}</article><article className="module-panel"><h2>Tendencia de emergencias</h2><div className="trend-chart" aria-label="Tendencia basada en los registros visibles">{Array.from({ length: 7 }, (_, index) => <i key={index} style={{ height: `${Math.max(12, items.filter((item) => { const d = new Date(item.fecha_registro); return !Number.isNaN(d.valueOf()) && Math.floor((Date.now() - d.valueOf()) / 86400000) === 6 - index; }).length * 28)}px` }} />)}</div><p className="module-caption">Registros de los últimos siete días.</p></article></div>
    <div className="module-panel"><div className="module-filters"><input placeholder="Buscar emergencia" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} /><select value={type} onChange={(e) => { setType(e.target.value); setPage(1); }}><option value="TODOS">Todos los tipos</option>{types.map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="TODOS">Todos los estados</option><option>ACTIVO</option><option>INACTIVO</option></select></div>
      <div className="module-table-wrap"><table className="module-table"><thead><tr><th>ID</th><th>Tipo</th><th>Descripción</th><th>Ubicación</th><th>Fecha / hora</th><th>Registrado por</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{records.map((item) => <tr key={item.PK_id}><td>{item.PK_id.slice(0, 8)}</td><td>{item.tipo}</td><td>{item.descripcion}</td><td>{item.ubicacion}</td><td>{new Date(item.fecha_registro).toLocaleString()}</td><td>{item.registrado_por}</td><td><span className={`module-status module-status--${item.estado.toLowerCase()}`}>{item.estado}</span></td><td className="module-actions"><button onClick={() => setDetail(item)}>Ver</button><button onClick={() => setEditing(item)}>Editar</button><button onClick={() => { emergencyRepository.toggleStatus(item.PK_id); refresh(); }}>{item.estado === "ACTIVO" ? "Desactivar" : "Activar"}</button><button className="danger" onClick={() => { if (window.confirm("¿Eliminar esta emergencia?")) { emergencyRepository.remove(item.PK_id); refresh(); } }}>Eliminar</button></td></tr>)}</tbody></table>{!records.length && <p className="module-empty">No se encontraron emergencias.</p>}</div><div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page} de {pages}</span><button disabled={page === pages} onClick={() => setPage(page + 1)}>Siguiente</button></div>
    </div>
    {(editing || detail) && <div className="module-dialog-backdrop" role="presentation"><section className="module-dialog" role="dialog" aria-modal="true"><button className="module-dialog__close" onClick={() => { setEditing(null); setDetail(null); }}>×</button>{detail ? <><h2>{detail.nombre_lugar}</h2><dl className="module-detail"><dt>Tipo</dt><dd>{detail.tipo}</dd><dt>Descripción</dt><dd>{detail.descripcion}</dd><dt>Ubicación</dt><dd>{detail.ubicacion}</dd><dt>Teléfono</dt><dd>{detail.telefono}</dd><dt>Registrado por</dt><dd>{detail.registrado_por}</dd></dl></> : <><h2>{editing === "new" ? "Registrar emergencia" : "Editar emergencia"}</h2><EmergencyForm value={editing === "new" ? emptyForm : editing!} onCancel={() => setEditing(null)} onSave={save} /></>}</section></div>}
  </section>;
}
